
title: "Machine Learning"
email: korbinian.riedhammer@fh-rosenheim.de
description: "Materials for Machine Learning (ML)"

url: "https://hsro-inf-ml.github.io"
baseurl: ""

exclude:
  - "LICENSE"
  - "Remarks.md"

github_username: ["sikoried"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
